// scenarios/farm/achievements.js — Farm achievement definitions
// Exposes window.FarmAchievements. Loaded before script.js.
// check(s) and progress(s) receive the game state object as first argument.

window.FarmAchievements = [
    { id: 'chicken_1',      i18nKey: 'ach_chicken_1',      title: 'FIRST CHICKEN',  desc: 'Buy your first chicken',
      check: s => s.chickens >= 1,
      progress: s => ({ cur: s.chickens, max: 1 }) },
    { id: 'chicken_25',     i18nKey: 'ach_chicken_25',     title: '25 CHICKENS',    desc: 'Have 25 chickens at once',
      check: s => (s.chickensWeighted ?? s.chickens) >= 25,
      progress: s => ({ cur: s.chickensWeighted ?? s.chickens, max: 25 }) },
    { id: 'chicken_250',    i18nKey: 'ach_chicken_250',    title: '250 CHICKENS',   desc: 'Have 250 chickens at once',
      check: s => (s.chickensWeighted ?? s.chickens) >= 250,
      progress: s => ({ cur: s.chickensWeighted ?? s.chickens, max: 250 }) },
    { id: 'chicken_500',    i18nKey: 'ach_chicken_500',    title: '500 CHICKENS',   desc: 'Have 500 chickens at once',
      check: s => (s.chickensWeighted ?? s.chickens) >= 500,
      progress: s => ({ cur: s.chickensWeighted ?? s.chickens, max: 500 }) },
    { id: 'chick_1',        i18nKey: 'ach_chick_1',        title: 'FIRST CHICK!',   desc: 'Hatch your first chick',
      check: s => (s.totalChicksBorn || 0) >= 1,
      progress: s => ({ cur: s.totalChicksBorn || 0, max: 1 }) },
    { id: 'chicks_100',     i18nKey: 'ach_chicks_100',     title: '100 CHICKS',     desc: 'Breed 100 chicks total',
      check: s => (s.totalChicksBorn || 0) >= 100,
      progress: s => ({ cur: s.totalChicksBorn || 0, max: 100 }) },
    { id: 'pet_10k',        i18nKey: 'ach_pet_10k',        title: 'PET MANIAC',     desc: 'Pet chickens 10,000 times',
      check: s => (s.totalPets || 0) >= 10000,
      progress: s => ({ cur: s.totalPets || 0, max: 10000 }) },
    { id: 'eggs_50k',       i18nKey: 'ach_eggs_50k',       title: 'EGG DEALER',     desc: 'Sell 50,000 eggs',
      check: s => (s.eggsSold || 0) >= 50000,
      progress: s => ({ cur: s.eggsSold || 0, max: 50000 }) },
    { id: 'retire',         i18nKey: 'ach_retire',         title: 'RETIRED!',       desc: 'Complete a game (retire)',
      check: s => !!s.hasRetired,
      progress: s => ({ cur: s.hasRetired ? 1 : 0, max: 1 }) },
    { id: 'perfect_retire', i18nKey: 'ach_perfect_retire', title: 'PERFECT FARM',   desc: 'Retire without any chicken suffering or dying of hunger',
      check: s => !!s.hasRetired && (s.deadChickens || 0) === 0 && (s.chickensSuffered || 0) === 0,
      progress: s => ({ cur: ((s.deadChickens || 0) === 0 && (s.chickensSuffered || 0) === 0) ? 1 : 0, max: 1 }) },
    { id: 'all_chals',      i18nKey: 'ach_all_chals',      title: 'CHALLENGER',     desc: 'Beat all 4 challenges',
      check: () => ['Vanilla','Speedrun','Adam','Manual'].every(c => localStorage.getItem('chickenIdleBeaten'+c) === 'true'),
      progress: () => ({ cur: ['Vanilla','Speedrun','Adam','Manual'].filter(c => localStorage.getItem('chickenIdleBeaten'+c) === 'true').length, max: 4 }) },
    { id: 'manual_10k',     i18nKey: 'ach_manual_10k',     title: 'EGG HUSTLER',   desc: 'Move 10,000 eggs manually',
      check: s => (s.manualEggsMovedToMarket || 0) >= 10000,
      progress: s => ({ cur: s.manualEggsMovedToMarket || 0, max: 10000 }) },
    { id: 'earn_1m',        i18nKey: 'ach_earn_1m',        title: 'MILLIONAIRE',   desc: 'Earn $1,000,000',
      check: s => (s.totalEarnings || 0) >= 1000000,
      progress: s => ({ cur: s.totalEarnings || 0, max: 1000000 }) },
    { id: 'earn_50m',       i18nKey: 'ach_earn_50m',       title: 'BIG BUSINESS',  desc: 'Earn $50,000,000',
      check: s => (s.totalEarnings || 0) >= 50000000,
      progress: s => ({ cur: s.totalEarnings || 0, max: 50000000 }) },
    { id: 'earn_1b',        i18nKey: 'ach_earn_1b',        title: 'BILLIONAIRE',   desc: 'Earn $1,000,000,000',
      check: s => (s.totalEarnings || 0) >= 1000000000,
      progress: s => ({ cur: s.totalEarnings || 0, max: 1000000000 }) },
    { id: 'earn_100b',      i18nKey: 'ach_earn_100b',      title: 'INSANE WEALTH', desc: 'Earn $100,000,000,000',
      check: s => (s.totalEarnings || 0) >= 100000000000,
      progress: s => ({ cur: s.totalEarnings || 0, max: 100000000000 }) },
];
