// shared/iap.js — "Remove Ads" in-app purchase (Google Play Billing only).
// Ported from OLD/TheMachinEgg_OLD/script.js, using the SAME package that
// already worked there: cordova-plugin-purchase (window.CdvPurchase / window.store).
//
// Unlike AdMob (a genuine Capacitor-native plugin), this is a real Cordova
// plugin, loaded through Capacitor's own Cordova-compatibility bridge
// (cordova.js + cordova_plugins.js, generated by "npx cap sync android" —
// see android/capacitor-cordova-android-plugins/ and
// android/app/src/main/assets/public/cordova_plugins.js). No hand-vendored
// UMD bundle needed or wanted here — an earlier attempt at vendoring the
// newer `capacitor-plugin-cdv-purchase` package via rollup hit an internal
// namespace-initialization bug in that package's own dist build. This one
// avoids all of that.
//
// Restricted to portrait mode only (desktop/tablet-landscape UI never shows or
// initializes this — see _active() below).
//
// Setup (call once after BGM is ready, same timing as GameAds.init()):
//   GameIAP.init({
//       onAdsRemoved: (isPreregister) => { ... }, // fired ONLY at the moment a
//                                                  // purchase transaction is
//                                                  // approved (drives the
//                                                  // one-time pre-register toast).
//       onOwnershipSync: (owned) => { ... },       // fired on every store.ready()
//                                                  // with the CURRENT true/false
//                                                  // entitlement — callers must
//                                                  // set state.adsRemoved = owned
//                                                  // (not just OR it to true),
//                                                  // so a refund correctly
//                                                  // brings ads back.
//       onReady: () => { ... }, // fired on store.ready() AND on productUpdated()
//                               // (offer/pricing metadata loads AFTER ready() —
//                               // canPurchase() depends on it, so callers must
//                               // re-render the buy button on both events, not
//                               // just once at page load).
//   })

window.GameIAP = (() => {
    const REMOVE_ADS_ID      = 'remove_ads_permanent';
    const PREREGISTER_ID     = 'preregister_remove_ads';

    let _onAdsRemoved    = null;
    let _onOwnershipSync = null;
    let _onReady         = null;
    let _ready           = false;
    // Última propiedad conocida, cacheada — la propiedad es un hecho GLOBAL de
    // la cuenta de Google, pero state.adsRemoved vive dentro de state, que se
    // recarga ENTERO en cada cambio de modo (loadState() por save-slot). Sin
    // este caché, onOwnershipSync solo se aplicaba una vez al arrancar; un
    // modo nunca jugado (save nuevo, adsRemoved:false por defecto) se quedaba
    // sin sincronizar y volvía a mostrar anuncios tras cambiar de modo.
    let _lastKnownOwned  = null;

    const STORE_GOOGLE = ['google', 'play'].join('');
    const STORE_APPLE  = 'appstore';

    function _active() {
        const isMobileMarket = (window.GAME_MARKET === STORE_GOOGLE || window.GAME_MARKET === STORE_APPLE);
        return isMobileMarket
            && window.GAME_MODE === 'portrait'
            && !!window.CdvPurchase;
    }

    // window.CdvPurchase / window.store solo existen una vez que el bootstrap
    // de Cordova termina de cargar todos los plugins (evento "deviceready",
    // asíncrono) — puede tardar un poco más que el resto de la página, así
    // que se reintenta en vez de rendirse a la primera.
    function init({ onAdsRemoved, onOwnershipSync, onReady } = {}) {
        _onAdsRemoved    = onAdsRemoved || null;
        _onOwnershipSync = onOwnershipSync || null;
        _onReady         = onReady || null;

        const isMobileMarket = (window.GAME_MARKET === STORE_GOOGLE || window.GAME_MARKET === STORE_APPLE);
        if (!isMobileMarket || window.GAME_MODE !== 'portrait') return;

        let attemptsLeft = 150; // ~15s a 100ms por intento
        (function tryInit() {
            if (window.CdvPurchase && window.CdvPurchase.store) { _register(); return; }
            if (--attemptsLeft > 0) { setTimeout(tryInit, 100); return; }
            console.warn('[IAP] window.CdvPurchase nunca apareció, GameIAP se queda inactivo');
        })();
    }

    function _register() {
        const store       = window.CdvPurchase.store;
        const ProductType = window.CdvPurchase.ProductType;
        const Platform     = window.CdvPurchase.Platform;
        const activePlatform = window.GAME_MARKET === STORE_APPLE ? (Platform.APPLE_APPSTORE || Platform.TEST) : Platform.GOOGLE_PLAY;

        store.register([
            { id: REMOVE_ADS_ID,  type: ProductType.NON_CONSUMABLE, platform: activePlatform },
            { id: PREREGISTER_ID, type: ProductType.NON_CONSUMABLE, platform: activePlatform },
        ]);

        store.when().approved((transaction) => {
            const isPreregister = (transaction.products || []).some(p => p.id === PREREGISTER_ID);
            _lastKnownOwned = true;
            _onAdsRemoved?.(isPreregister);
            transaction.finish();
        });

        // Fired when product/offer metadata arrives from Play Billing — this can
        // (and usually does) happen AFTER store.ready(), which only means the
        // billing connection itself is up. canPurchase() needs the offer, so the
        // "remove ads" button must be re-checked here too, not just on ready().
        store.when().productUpdated(() => {
            _onReady?.();
        });

        store.error((e) => console.warn('[IAP] store error:', e));

        store.initialize([activePlatform]);

        store.ready(() => {
            _ready = true;
            // Sincroniza SIEMPRE con la propiedad real reportada por Play Billing
            // (en ambas direcciones) — si no, un reembolso posterior a una compra
            // nunca revertiría state.adsRemoved, porque antes solo se ponía a
            // true y jamás se volvía a comprobar.
            const owned = store.owned(REMOVE_ADS_ID) || store.owned(PREREGISTER_ID);
            _lastKnownOwned = owned;
            _onOwnershipSync?.(owned);
            _onReady?.();
        });
    }

    // Whether the "remove ads" button should be shown (not owned yet, offer available).
    function canPurchase() {
        if (!_active() || !_ready) return false;
        try {
            const p = window.CdvPurchase.store.get(REMOVE_ADS_ID);
            return !!p && !p.owned && !!p.getOffer?.();
        } catch (e) { return false; }
    }

    // Última propiedad conocida (true/false), o null si aún no se sabe (store
    // todavía no ha llegado a ready() en ningún momento de esta sesión).
    function isOwned() { return _lastKnownOwned; }

    function purchase() {
        if (!_active()) return;
        try {
            const p = window.CdvPurchase.store.get(REMOVE_ADS_ID);
            const offer = p?.getOffer?.();
            if (offer) window.CdvPurchase.store.order(offer);
        } catch (e) { console.warn('[IAP] purchase failed:', e); }
    }

    return { init, canPurchase, purchase, isOwned };
})();
